### ISSUE TITLE
Do not use system.drawing for iamges

### ISSUE THREAD

**Issue by Miepee** [UltiNaruto/YAPR#3]
Doesnt work on anywhere except windows. Use imagesharp instead

**Comment by UltiNaruto** [comment]
Not an issue for now since Planets doesn't work on anything except Windows. Might be a concern for later though.

**Comment by Miepee** [comment]
It is an issue because the patcher will be run on non windows systems.

**Comment by UltiNaruto** [comment]
so mostly for tests?

**Comment by Miepee** [comment]
no. its a perfectly valid usecase on linux to run the patcher natively but then run the game itself through wine.
